export const loadingData = [
  {
    id: 1,
    style: {
      position: "absolute",
      width: "10px",
      height: "10px",
      borderRadius: "50%",
      display: "inline-block",
      backgroundColor: "blue",
      transform: "rotate(calc(1 * (360deg / 15))) translateY(35px)",
      animationDelay: "calc(1 * .1s)",
      opacity: "0",
    },
  },
  {
    id: 2,
    style: {
      position: "absolute",
      width: "10px",
      height: "10px",
      borderRadius: "50%",
      display: "inline-block",
      backgroundColor: "blue",
      transform: "rotate(calc(2 * (360deg / 15))) translateY(35px)",
      animationDelay: "calc(2 * .1s)",
      opacity: "0",
    },
  },
  {
    id: 3,
    style: {
      position: "absolute",
      width: "10px",
      height: "10px",
      borderRadius: "50%",
      display: "inline-block",
      backgroundColor: "blue",
      transform: "rotate(calc(3 * (360deg / 15))) translateY(35px)",
      animationDelay: "calc(3 * .1s)",
      opacity: "0",
    },
  },
  {
    id: 4,
    style: {
      position: "absolute",
      width: "10px",
      height: "10px",
      borderRadius: "50%",
      display: "inline-block",
      backgroundColor: "blue",
      transform: "rotate(calc(4*(360deg / 15))) translateY(35px)",
      animationDelay: "calc(4 * .1s)",
      opacity: "0",
    },
  },
  {
    id: 5,
    style: {
      position: "absolute",
      width: "10px",
      height: "10px",
      borderRadius: "50%",
      display: "inline-block",
      backgroundColor: "blue",
      transform: "rotate(calc(5 * (360deg / 15))) translateY(35px)",
      animationDelay: "calc(5 * .1s)",
      opacity: "0",
    },
  },
  {
    id: 6,
    style: {
      position: "absolute",
      width: "10px",
      height: "10px",
      borderRadius: "50%",
      display: "inline-block",
      backgroundColor: "blue",
      transform: "rotate(calc(6 * (360deg / 15))) translateY(35px)",
      animationDelay: "calc(6 * .1s)",
      opacity: "0",
    },
  },
  {
    id: 7,
    style: {
      position: "absolute",
      width: "10px",
      height: "10px",
      borderRadius: "50%",
      display: "inline-block",
      backgroundColor: "blue",
      transform: "rotate(calc(7 * (360deg / 15))) translateY(35px)",
      animationDelay: "calc(7 * .1s)",
      opacity: "0",
    },
  },
  {
    id: 8,
    style: {
      position: "absolute",
      width: "10px",
      height: "10px",
      borderRadius: "50%",
      display: "inline-block",
      backgroundColor: "blue",
      transform: "rotate(calc(8 * (360deg / 15))) translateY(35px)",
      animationDelay: "calc(8 * .1s)",
      opacity: "0",
    },
  },
  {
    id: 9,
    style: {
      position: "absolute",
      width: "10px",
      height: "10px",
      borderRadius: "50%",
      display: "inline-block",
      backgroundColor: "blue",
      transform: "rotate(calc(9 * (360deg / 15))) translateY(35px)",
      animationDelay: "calc(9 * .1s)",
      opacity: "0",
    },
  },
  {
    id: 10,
    style: {
      position: "absolute",
      width: "10px",
      height: "10px",
      borderRadius: "50%",
      display: "inline-block",
      backgroundColor: "blue",
      transform: "rotate(calc(10 * (360deg / 15))) translateY(35px)",
      animationDelay: "calc(10 * .1s)",
      opacity: "0",
    },
  },
  {
    id: 11,
    style: {
      position: "absolute",
      width: "10px",
      height: "10px",
      borderRadius: "50%",
      display: "inline-block",
      backgroundColor: "blue",
      transform: "rotate(calc(11 * (360deg / 15))) translateY(35px)",
      animationDelay: "calc(11 * .1s)",
      opacity: "0",
    },
  },
  {
    id: 12,
    style: {
      position: "absolute",
      width: "10px",
      height: "10px",
      borderRadius: "50%",
      display: "inline-block",
      backgroundColor: "blue",
      transform: "rotate(calc(12 * (360deg / 15))) translateY(35px)",
      animationDelay: "calc(12 * .1s)",
      opacity: "0",
    },
  },
  {
    id: 13,
    style: {
      position: "absolute",
      width: "10px",
      height: "10px",
      borderRadius: "50%",
      display: "inline-block",
      backgroundColor: "blue",
      transform: "rotate(calc(13 * (360deg / 15))) translateY(35px)",
      animationDelay: "calc(13 * .1s)",
      opacity: "0",
    },
  },
  {
    id: 14,
    style: {
      position: "absolute",
      width: "10px",
      height: "10px",
      borderRadius: "50%",
      display: "inline-block",
      backgroundColor: "blue",
      transform: "rotate(calc(14 * (360deg / 15))) translateY(35px)",
      animationDelay: "calc(14 * .1s)",
      opacity: "0",
    },
  },
  {
    id: 15,
    style: {
      position: "absolute",
      width: "10px",
      height: "10px",
      borderRadius: "50%",
      display: "inline-block",
      backgroundColor: "blue",
      transform: "rotate(calc(15 * (360deg / 15))) translateY(35px)",
      animationDelay: "calc(15 * .1s)",
      opacity: "0",
    },
  },
];
